# Generated by Django 3.0.6 on 2020-10-08 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=250, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('rupees', models.CharField(max_length=100)),
                ('hourorday', models.CharField(max_length=100)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=40)),
                ('maxamount', models.IntegerField()),
                ('maxdays', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bids', models.ManyToManyField(blank=True, to='app.WorkerProfile')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.UserProfile')),
            ],
        ),
    ]
