# Generated by Django 3.0.6 on 2020-10-08 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201008_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 10, 8, 3, 3, 46, 262655)),
        ),
    ]
