# Generated by Django 3.1.2 on 2021-06-03 04:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201008_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 3, 10, 7, 43, 612883)),
        ),
    ]
