# Generated by Django 3.1.2 on 2021-06-03 10:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210603_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='bids',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='gender',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 3, 16, 29, 0, 442920)),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.work')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.workerprofile')),
            ],
        ),
    ]
