# Generated by Django 3.0.14 on 2021-06-07 05:36

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210603_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='proposal_days',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='proposal_price',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 11, 5, 40, 547313)),
        ),
    ]
