# Generated by Django 3.0.14 on 2021-06-07 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210607_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 7, 14, 10, 10, 437320)),
        ),
        migrations.AlterField(
            model_name='work',
            name='maxamount',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='work',
            name='maxdays',
            field=models.CharField(max_length=40),
        ),
    ]
