# Generated by Django 3.0.14 on 2021-06-10 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210607_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='isassigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 10, 16, 20, 31, 651251)),
        ),
    ]
